C:
cd TC\BIN\
path c:\tc\bin;%path%
tcc -IC:\TC\BIN\XINU4WIN\NEWSRC -eC:\TC\BIN\XINU4WIN\NEWSRC\EXAMPLES\ex1.exe C:\TC\BIN\XINU4WIN\NEWSRC\EXAMPLES\ex1.c C:\TC\BIN\XINU4WIN\NEWSRC\XINU.LIB
C:\TC\BIN\XINU4WIN\NEWSRC\EXAMPLES\ex1.exe